// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Fundflow",
  description: "On-Chain Crowdfunding Platform",
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[color:var(--ff-bg)] text-[color:var(--ff-text)] font-dm-sans antialiased min-h-screen">
        {/* Ambient background blobs */}
        <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden">
          <div className="absolute -top-44 -left-44 w-[640px] h-[640px] rounded-full bg-[color:var(--ff-accent)]/6 blur-[130px]" />
          <div className="absolute top-1/2 -right-72 w-[560px] h-[560px] rounded-full bg-[color:var(--ff-accent-2)]/7 blur-[150px]" />
          <div className="absolute bottom-0 left-1/3 w-[460px] h-[460px] rounded-full bg-[color:var(--ff-accent)]/4 blur-[120px]" />
        </div>

        <Navbar />

        <main className="relative z-10 pt-[72px]">{children}</main>
      </body>
    </html>
  );
}
